spring:
  datasource:
    url: jdbc:sqlserver://localhost;database=J6Store
    username: sa
    password: NguyenVanSuong@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      show-sql: true
      format-sql: true